In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# Concatenate

In [4]:
arr1 = np.arange(9).reshape(3,3)

In [5]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr2 = np.arange(9).reshape(3,3)

In [7]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.concatenate([arr1,arr2],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [11]:
s1 = Series([1,2,3], index=['X','Y','Z'])

In [12]:
s2 = Series([4,5], index=['A','B'])

In [13]:
s1

X    1
Y    2
Z    3
dtype: int64

In [14]:
s2

A    4
B    5
dtype: int64

In [15]:
pd.concat([s1,s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [27]:
df1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [28]:
df1

X         Y         Z
0  0.322806  1.203908  1.323285
1  0.683237 -0.149916 -0.790159
2 -0.402874  1.016198  0.387071
3 -0.352442  1.404977 -1.130310

In [29]:
df2 = DataFrame(np.random.randn(3,3), columns=['X','Y','A'])

In [30]:
df2

X         Y         A
0  0.802874  0.524320  0.817666
1  0.412476 -0.252169 -0.628174
2 -0.272540 -0.614410  0.375202

In [32]:
pd.concat([df1,df2])

A         X         Y         Z
0       NaN  0.322806  1.203908  1.323285
1       NaN  0.683237 -0.149916 -0.790159
2       NaN -0.402874  1.016198  0.387071
3       NaN -0.352442  1.404977 -1.130310
0  0.817666  0.802874  0.524320       NaN
1 -0.628174  0.412476 -0.252169       NaN
2  0.375202 -0.272540 -0.614410       NaN

In [33]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'

# Combine

In [34]:
s1 = Series([2, np.nan, 4, np.nan], index=['A','B','C','D'])

In [35]:
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [36]:
s2 = Series([1,2,3,4], index=['A','B','C','D'])

In [37]:
s2

A    1
B    2
C    3
D    4
dtype: int64

In [38]:
s1.combine_first(s2)

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [39]:
df1 = DataFrame({
    'X': [1, np.nan, 3, np.nan],
    'Y': [5, np.nan, 7, np.nan],
    'Z': [9, np.nan, 11,np.nan]
})

In [40]:
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [41]:
df2 = DataFrame({
    'Z':[np.nan, 10, np.nan, 12],
    'A':[1,2,3,4]
})

In [42]:
df2

A     Z
0  1   NaN
1  2  10.0
2  3   NaN
3  4  12.0

In [43]:
df1.combine_first(df2)

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0