# 数组的创建和访问

In [1]:
import numpy as np

In [2]:
# create from python list
list_1 = [1, 2, 3, 4]

In [3]:
list_1

[1, 2, 3, 4]

In [4]:
array_1 = np.array(list_1)

In [5]:
array_1

array([1, 2, 3, 4])

In [6]:
list_2 = [5, 6, 7, 8]

In [7]:
array_2 = np.array([list_1, list_2])

In [8]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
array_2.shape

(2, 4)

In [10]:
array_2.size

8

In [11]:
array_2.dtype

dtype('int64')

In [13]:
array_3 = np.array([[1.0,2,3],[4.0,5,6]])

In [14]:
array_3.dtype

dtype('float64')

In [17]:
array_4 = np.arange(1, 10, 2)

In [18]:
array_4

array([1, 3, 5, 7, 9])

In [19]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [20]:
np.zeros([2,3])

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [21]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [22]:
np.eye(5).dtype

dtype('float64')

In [23]:
a = np.arange(1,10)

In [24]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a[1]

2

In [26]:
a[1:5]

array([2, 3, 4, 5])

In [27]:
b = np.array([[1,2,3],[4,5,6]])

In [28]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b[1][0]

4

In [30]:
b[1,0]

4

In [33]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [34]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
c[:2,1:]

array([[2, 3],
       [5, 6]])