# 使用pickle序列化numpy array

In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
f = open('x.pkl', 'wb')

In [5]:
pickle.dump(x, f)

In [6]:
!ls

Array.ipynb                  x.pkl
Array的input和output.ipynb   数组与矩阵运算.ipynb


In [7]:
f = open('x.pkl', 'rb')

In [8]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.save('one_array', x)

In [10]:
!ls

Array.ipynb                  x.pkl
Array的input和output.ipynb   数组与矩阵运算.ipynb
one_array.npy


In [11]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
y = np.arange(20)

In [13]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.savez('two_array.npz', a=x, b=y)

In [15]:
!ls

Array.ipynb                  two_array.npz
Array的input和output.ipynb   x.pkl
one_array.npy                数组与矩阵运算.ipynb


In [17]:
c = np.load('two_array.npz')

In [18]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])